script: |
  cd /var/www/html/cloud-storage
  git fetch origin
  git reset --hard origin/main
  /var/www/html/cloud-storage/venv/bin/pip install -r requirements.txt
  sudo systemctl restart cloud-storage
  sudo systemctl status cloud-storage --no-pager

